### ISSUE TITLE
Versions schema

### ISSUE THREAD

**Issue by denizzzka** [DerelictOrg/DerelictPQ#15]
Probably, if changes affects functions or arguments names it is need to increment minor version instead of patch version. Otherwise, build breaks down unexpectedly for application what uses version like "~>x.y.z" in DUB config.

**Comment by denizzzka** [comment]
I.e., version 2.0.1 should be 2.1.0

**Comment by aldacron** [comment]
Yes, normally I would agree with you. I don't think it really matters in this case though.

**Comment by denizzzka** [comment]
It is brokes my code :(

**Comment by aldacron** [comment]
Yeah, but if I had tagged 2.1, which included your const fixes, there would have been no 2.0.x and you would have started using 2.1 anyway with the same result? Correct? I don't see the difference :)

**Comment by denizzzka** [comment]
My const fixes also breaks backward compatibility. Any change to functions prototypes breaks code.
