### ISSUE TITLE
Posix custom library name

### ISSUE THREAD

**Issue by anton-dutov** [DerelictOrg/DerelictPQ#19]
In some distros (Like Debian) libpq come with name "libpq.so.5", and no soft link libpq.so -> libpq.so.5

Any hack to customize  `enum libNames = "libpq.so"`?

**Comment by denizzzka** [comment]
I am haven't any problem with this package in Debian

**Comment by mdparker** [comment]
> In some distros (Like Debian) libpq come with name "libpq.so.5", and no soft link libpq.so -> libpq.so.5

Is this true for all of the 9.x series, or just a specific version?

> Any hack to customize enum libNames = "libpq.so"?

Future proof:
```d
version(linux) {
    import derelict.util.exception;
    try { DerelictPQ.load("libpq.so.5"); }
    catch(SharedLibLoadException slle) { DerelictPQ.load(); }
}
```

In this specific case:

```d
version(linux) DerelictPQ.load("libpq.so, libpq.so.5");
```

If you can verify the versions to which this naming scheme applies, I can add it to the DerelictPQ loader.

**Comment by anton-dutov** [comment]
@denizzzka, @mdparker  omewhere i use testing branch

    # ls -1 /usr/lib/x86_64-linux-gnu | grep libpq
    libpq.a
    libpq.so.5
    libpq.so.5.9


Thank you, that work fine

    version(linux) DerelictPQ.load("libpq.so, libpq.so.5");
