### ISSUE TITLE
The description on code.dlang.org says it's for GLFW3

### ISSUE THREAD

**Issue by zachthemystic** [DerelictOrg/DerelictPQ#20]
It's for PQ!

**Comment by denizzzka** [comment]
Bump!

**Comment by mdparker** [comment]
I don't see anyway to fix this myself, short of deleting the package an re-registering it. There's no option on the package management page to change the description. I'll see if there's an enhancement request for it and submit one if not.

**Comment by denizzzka** [comment]
Confirmed: https://github.com/dlang/dub-registry/issues/200

**Comment by denizzzka** [comment]
Seems like fixed for this package

**Comment by mdparker** [comment]
Right. I figured out later on how to change it but forgot about closing this issue. Thanks!
