### ISSUE TITLE
function PQexecPrepared 

### ISSUE THREAD

**Issue by anton-dutov** [DerelictOrg/DerelictPQ#8]
In pq.d function defined as:

    alias da_PQexecPrepared = PGresult* function(PGconn* conn, char* stmtName, int nParams, char** paramValues, int* paramFormats, int resultFormat);

But in documentation function defined as:

    PGresult *PQexecPrepared(PGconn *conn,
                         const char *stmtName,
                         int nParams,
                         const char * const *paramValues,
                         const int *paramLengths,
                         const int *paramFormats,
                         int resultFormat);

Argument *paramLengths* missing.

**Comment by aldacron** [comment]
Thanks! The fix is pushed and will be available in version 1.0.1 as soon as the dub registry updates.
